name: Build-Windows-EXE
on: [push]
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install Libs
        run: pip install pyinstaller pynput pyautogui numpy pywin32 Pillow
      - name: Build
        run: pyinstaller --noconsole --onefile --admin main.py
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Bot_Zensware_EXE
          path: dist/main.exe
          
